### ISSUE TITLE
Easy way to override asset for local development?

### ISSUE THREAD

**Issue by nmichlo** [Cornerstone-OnDemand/modelkit#168]
Is there an easy way to override an asset in a config specifically for development / non-production purposes?

Ideally, a way to do this on the local machine by copying an existing config, and setting the asset path to a local directory. Even if before it pointed to a remote path.

**Comment by nmichlo** [comment]
For example, maybe support for `asset: "file:///test/path/to/asset"` which then bypasses the asset resolver?

**Comment by nmichlo** [comment]
Closing, missed this:
```yaml
model_name:
    asset: asset/name:1.0/[file.ext]
    model_settings:
        asset_path: /local/path/to/asset/file.ext
```
